### ISSUE TITLE
Changeable fields feature

### ISSUE THREAD

**Issue by MekBoss** [Saican/ZSWin#5]
Is it planned to add to the project fields to change? I mean sliders, on/off switches, etc.

**Comment by Saican** [comment]
I'd love to see a textbox control, but I think we'd need a pretty significant interface to take keyboard input and translate that into a string on the screen.  So that one would be a far flung feature - something to work on but not top priority.

Buttons already have Radio and Check variants, controlled by the button's type.  There's no default code for these buttons, so you'd have to set one up like the "Close" or "BFG Button"; those are just descendents of ZButton doing the job their names imply.

I'm 100% open to control code submissions, so if you'd like to take a stab at sliders, go for it.  I'll gladly answer any questions you have :)

**Comment by MekBoss** [comment]
Hmmmm, but keyboard input work for console and for save game naming.
Even more, if you use mouse only in savegame menu Gzdoom will show on screen keyboard overlay (just open save game submenu, press using cursor on "save a new game" or any saved game name name)

**Comment by Saican** [comment]
[Today's commit](https://github.com/Saican/ZSWin/commit/2ec7842b13e0259ab9724be358b15ccbe3ad6710l) might peak your interest.

**Comment by Saican** [comment]
Closing this, solution presented and haven't received any further input.

**Comment by MekBoss** [comment]
Ahhh, real life things and other project.

**Comment by Saican** [comment]
No problem, real-life takes precedence over a Doom mod.  If you mess around with the extended event methods and encounter any problems let me know, documentation is really behind right now, so I'll gladly explain anything that's not clear.  I can also elevate other events as needed.
