### ISSUE TITLE
I Broke Multiplayer - Again

### ISSUE THREAD

**Issue by Saican** [Saican/ZSWin#7]
Event elevation made me start thinking about singular thinkers versus multiple event handlers and I realized that the zEvent member is probably breaking multiplayer.  What event handler is it getting?  Is it the handler that corresponds to the thinker's PlayerClient?  In multiplayer, probably not.

Options:
Search for the right handler - not sure if I can do that.
Change every last interaction into a net event - probably the solution.

@MekBoss, this is another note for myself more than anything, but if you have ideas I'm all ears.

Edit: I apologize to the other mek from, I think Ohio, I may have accidentally mentioned, if you get some email about this or something, I meant the other mek, not that mek! lol sorry!

**Comment by MekBoss** [comment]
Turn entire menu system to UI scope. It will prevent all network Zscript related bugs, since UI things (like render overlays or native Gzdoom menus) happens ONLY on Gzdoom instance that execute it and not shared between connected Gzdoom instances.

Here I tried to create more OOP based system for drawing stuff on screen. But then I realized that I need file parser, than that I need more optimized way to control classes, then that I need primitive state machine, than.... so now I miles away from main point of this project and writing much faster collision detection for actors using Zscript, because I realize that my weather library can be optimized,
https://github.com/MekBoss/gzdoom-2d-OOP
It have a lot of placeholders and currently in state "proof of concept". Check UI ticker and render overlay virtual here
[Main ticker](https://github.com/MekBoss/gzdoom-2d-OOP/blob/master/2d_animator/2d_classes/back_end/screen_ticker.zc)
And here class which contain all info about textures and it orientation/position/scale/etc.
[Screen entity](https://github.com/MekBoss/gzdoom-2d-OOP/blob/master/2d_animator/2d_classes/back_end/screen_entity.zc)
Note that everything screen related have ui scope, like `class screen_entity ui`. [Object ](https://zdoom.org/wiki/Object) class in Zscript have data scope, which can be changed to play or ui. Logic/visual ticks virtual also important, but I dont think they would have much of impact for menus, since there are no collision detection, menu states changing, etc.

It have some comments, so it wouldnt be much of a problem to figure out how this work, I think.

**Comment by Saican** [comment]
Its not really a scope problem.  The problem is there's one ZObject and multiple event handlers, each of them calling the event extension methods on that ZObject every, whatever tick scope the methods use.

So I'm glad I slept on this, I was overthinking it.  Filtering objects already exists, that's what the PlayerClient member is for, it's what player the ZObject corresponds to.  So the event handler methods just need to check that they are calling their extensions for the right player, just like RenderOverlay.

BUT, the problem runs in reverse as well.  The ZObject member ZEvent is a reference to the ZEventSystem - the event handler.  That's what the op was about.  By just using Find, in a multiplayer setup, that's just going to spit back the first ZEventSystem it finds, which is probably player 0's, which means ZObjects using their ZEvent member to send net events are probably doing so with the wrong event handler reference.  IF the objects are sending net events, it's probably no big deal because every handler should get the event.  BUT, direct ZEvent usage, say calling PostStackIndex, is going to be doing that on the wrong handler.

1 - So direct access is a no-no, those instances have to become net events.
2 - ZObjects need to send their PlayerClient along in net events so the handlers have some way to know which handler should respond. 


Lastly - is you gzdoom-2d-oop a 2D shape drawer?  I will be browsing that when I get around to making a 2d shape control.  Got textboxes most of the way there!

Lastly lastly - Up to now I've avoided file parsing of any kind, mostly just due to the fact that you have to write ZScript to use ZScript Windows, so on top of learning one api, why make users learn 2 in order to have their files parsed?  But, a few years ago I wrote an XML interpreter that has functionality similar to your JSON parser - iirc you created a system allowing for custom variable storage, which my interpreter also does, which I think is really really really cool, and I could see integrating your JSON parser to allow for huge flexibility like that.  Down the line though once things are more finalized.

**Comment by MekBoss** [comment]
To clarify, each player in netgame has its own event instance, but they all "connected" with each other. So player 0 dont have event 0 and a copy of all player events, it have same event as everyone, and EventHandler.Find(name) return same event for all 0-1-2-3-4-5-6-7 players. Engine differ player on playerinfo struct level.
Roughly speaking if Gzdoom sees data with "thing for player i" mark it check is player i-th exist, then pick its playerinfo struct and execute data using i-th player as caller.

>  is you gzdoom-2d-oop a 2D shape drawer

Triangle drawer, or something like that (texture rotation/shape modification)? No. Gzdoom support that but for some reason all calls to it in Zscript produce black squares on my PC. Why? Dont know. Maybe VM machine tries to use integrated videocard, maybe its a driver problem, maybe video card manufacturer forced forbidden execution of all draw calls from Gzdoom VM....
If it called from eehhhh actual programming languages it work flawlessly, but not from Zscript. And I cant create something I cant see.
But its easy to add such thing, since core code already there.

And JSON parser currently dont support arrays and IIRC have small problem with function which return parsed data.

**Comment by Saican** [comment]
[This commit](https://github.com/Saican/ZSWin/commit/9cca5dec1a8091c0a64d0ad397d38fd52cb1c3a7) should take care of this problem.  I apologize for the slow turnaround on this - I wasn't too thrilled to do this job, basically the entire command system got either ripped out or ripped apart and modified, as well as adding and losing some commands.

Finally, there's an answer to the debate here on event handlers versus thinkers; another question was whether activating UI mode for one player would do so for all.  The answer is no.  But that also gives insight into the original question: one handler or multiple?  The answer is both.  There's one handler for each player, each running an instance of GZDoom, running whatever mods on top of ZScript Windows.  Essentially each instance of the engine connected via the network is just "agreeing" on the status of a given running level, down to the vectors of each player.

In each GZDoom instance, any player can create a ZWindow.  But there's only the one ZWindow, which is assigned to a particular player; when a player creates a ZWindow, that thinker appears for every player.  This doesn't have to be the player that created the ZWindow - this is kind of an important thing to note, one player could activate a switch that seems to do nothing, but another player suddenly gets a window on their screen.  The other important thing is that every player's event system is aware of this thinker and can act on that thinker through events.  This is what event isolation is for - if a window or a control doesn't correspond to a player, the player's event system ignores it.  This also has to happen for events themselves.  The reason for this is that is is perfectly possible to change a ZObject's PlayerClient to another player number.  Imagine multiplayer UI actions: Star Trek self-destruct anyone? Multi-player-based crafting?  Checkers in Doom?

Lastly, if you're running on an integrated graphics chipset, depending on the age it may be incompatible the the current hardware renderer.  Try the software renderer(s); unless the shape drawer is a hardware restricted feature.
